// <auto-generated />
using System;
using ChocoFreseo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChocoFreseo.Migrations
{
    [DbContext(typeof(ChocoFreseoDbContext))]
    partial class ChocoFreseoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChocoFreseo.Models.Domain.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ChocoFreseo.Models.Domain.DetallePedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetallesPedido");
                });

            modelBuilder.Entity("ChocoFreseo.Models.Domain.DireccionCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barrio")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("bit");

                    b.Property<double?>("Latitud")
                        .HasColumnType("float");

                    b.Property<double?>("Longitud")
                        .HasColumnType("float");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Referencia")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("DireccionesCliente");
                });

            modelBuilder.Entity("ChocoFreseo.Models.Domain.Domicilio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostoDomicilio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("DireccionClienteId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoDomicilio")
                        .HasColumnType("int");

                    b.Property<DateTime?>("HoraAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HoraEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HoraSalida")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notas")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Propina")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("RepartidorId")
                        .HasColumnType("int");

                    b.Property<int?>("ZonaEntregaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DireccionClienteId");

                    b.HasIndex("PedidoId")
                        .IsUnique()
                        .HasFilter("[PedidoId] IS NOT NULL");

                    b.HasIndex("RepartidorId");

                    b.HasIndex("ZonaEntregaId");

                    b.ToTable("Domicilios");
                });

            modelBuilder.Entity("ChocoFreseo.Models.Domain.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoPedido")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("ChocoFreseo.Models.Domain.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("ChocoFreseo.Models.Domain.Repartidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Documento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Repartidores");
                });

            modelBuilder.Entity("ChocoFreseo.Models.Domain.ZonaEntrega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostoDomicilioBase")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("NombreZona")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("TiempoEstimadoMinutos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ZonasEntrega");
                });

            modelBuilder.Entity("ChocoFreseo.Models.Domain.DetallePedido", b =>
                {
                    b.HasOne("ChocoFreseo.Models.Domain.Pedido", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChocoFreseo.Models.Domain.Producto", "Producto")
                        .WithMany("DetallesPedido")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ChocoFreseo.Models.Domain.DireccionCliente", b =>
                {
                    b.HasOne("ChocoFreseo.Models.Domain.Cliente", "Cliente")
                        .WithMany("Direcciones")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ChocoFreseo.Models.Domain.Domicilio", b =>
                {
                    b.HasOne("ChocoFreseo.Models.Domain.DireccionCliente", "DireccionCliente")
                        .WithMany()
                        .HasForeignKey("DireccionClienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChocoFreseo.Models.Domain.Pedido", "Pedido")
                        .WithOne("Domicilio")
                        .HasForeignKey("ChocoFreseo.Models.Domain.Domicilio", "PedidoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChocoFreseo.Models.Domain.Repartidor", "Repartidor")
                        .WithMany("Domicilios")
                        .HasForeignKey("RepartidorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ChocoFreseo.Models.Domain.ZonaEntrega", "ZonaEntrega")
                        .WithMany()
                        .HasForeignKey("ZonaEntregaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DireccionCliente");

                    b.Navigation("Pedido");

                    b.Navigation("Repartidor");

                    b.Navigation("ZonaEntrega");
                });

            modelBuilder.Entity("ChocoFreseo.Models.Domain.Pedido", b =>
                {
                    b.HasOne("ChocoFreseo.Models.Domain.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ChocoFreseo.Models.Domain.Cliente", b =>
                {
                    b.Navigation("Direcciones");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("ChocoFreseo.Models.Domain.Pedido", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Domicilio");
                });

            modelBuilder.Entity("ChocoFreseo.Models.Domain.Producto", b =>
                {
                    b.Navigation("DetallesPedido");
                });

            modelBuilder.Entity("ChocoFreseo.Models.Domain.Repartidor", b =>
                {
                    b.Navigation("Domicilios");
                });
#pragma warning restore 612, 618
        }
    }
}
